spring:
  messages:
    basename: errors

  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/ssafyweb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
    mapper-locations: mapper/BookMapper.xml

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug

server.servlet.session:
  tracking-modes: cookie
  timeout: 1800

mybatis:
  configuration:
    map-underscore-to-camel-case: true